
name: Auto-Proxy-Scanner
on:
  schedule:
    - cron: "0 */8 * * *" # –ö–∞–∂–¥—ã–µ 8 —á–∞—Å–æ–≤
  workflow_dispatch: # –í–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å –∑–∞–ø—É—Å–∫–∞—Ç—å –≤—Ä—É—á–Ω—É—é

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }} # –¢–≤–æ–π —Ç–æ–∫–µ–Ω –¥–ª—è –¥–æ—Å—Ç—É–ø–∞ –∫ —Ä–µ–ø–æ

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests google-generativeai

      - name: Run Scanner
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # –¢–≤–æ–π –∫–ª—é—á Gemini
        run: python scanner.py

      - name: Commit and Push results
        run: |
          git config --local user.email "blondie@gemini.ai"
          git config --local user.name "Blondie-Bot"
          git add .
          git commit -m "üë±‚Äç‚ôÄÔ∏è Blondie: Auto-update (Configs & Channels)" || exit 0
          git push
